In [ ]:
import json 
import numpy as np 
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D, Attention
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder

#only keep those which are needed for pre processing

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
with open('/new_intents.json') as file:
    data = json.load(file)
    
training_sentences = []
training_labels = []
labels = []
responses = []


for intent in data['intents']:
    for pattern in intent['patterns']:
        training_sentences.append(pattern)
        training_labels.append(intent['tag'])
    responses.append(intent['responses'])
    
    if intent['tag'] not in labels:
        labels.append(intent['tag'])
        
num_classes = len(labels)

In [ ]:
labels #tags are stored

['About TRF', 'Greeting', 'Goodbye_Thanks', 'About', 'Robocon', 'Part of TRF ']

In [ ]:
training_sentences #patterns

['What is TRF?',
 "What's the motive of TRF?",
 'What exactly is TRF?',
 'What specifically is TRF?',
 'What necessarily is TRF?',
 "What is TRF's motivation?",
 'What basically is TRF?',
 "What is TRF's intention?",
 "What is TRF's desire?",
 "What is TRF's motto?",
 'What do we do in TRF?',
 'Is TRF a good club for me ?',
 'What does TRF focus on?',
 'What is TRF working for?',
 'What is the vision and mission of TRF?',
 'Hi',
 'Hey',
 'Is anyone there?',
 'Hello',
 'Greetings',
 'Good morning',
 'Hola!',
 ' Good Evening',
 'Hello Bot',
 'How you doing?',
 'What’s up',
 'Good Afternoon',
 'Bye',
 'See you later',
 'Goodbye',
 'Goodnight',
 'Thank You',
 'Thanks',
 'Thanks',
 'Thank you',
 "That's helpful",
 'Thanks for the help',
 'Thank you for helping out',
 'Your help is much appreciated',
 ' You are so kind',
 'You are very helpful',
 'Aren’t you a peach',
 'Wonderful Bot',
 'Gracias',
 'Appreciated your help',
 'Who are you?',
 'What are you?',
 'Who you are?',
 ' Can I know you

In [ ]:
responses #reponses from the bot

[["The Robotics Forum is VIT Pune's premier robotics club, with a 15-year legacy. Students from various engineering disciplines make up our varied community, all of whom are driven by a passion for robotics. The goal of the team is to gain new skills, explore new technologies, and promote the area of robotics."],
 ['Hello', 'Hi', 'Hi there', ' Hey, how can I help you?'],
 ['See you later',
  'Have a nice day',
  'Bye! Come back again',
  'Happy to help!',
  'Any time!',
  'My pleasure',
  "You're most welcome!"],
 ["I’m XYZ , your TRF assistant bot. I'm a NLP based bot made as a collaboration project of the ML and the Web team.",
  "I'm XYZ, an Artificial Intelligent bot based on NLP. I m here to provide you information about TRF and Robosoft. I was developed by the ML team and deployed by the Web team."],
 ['TRF participates in the ABU Robocon every year. In this competition robots built by different teams compete to perform a given task within a time frame. Anyone who is a member of 

In [ ]:
training_labels #2 patterrns for abt trf ke 2 questions and so on..

['About TRF',
 'About TRF',
 'About TRF',
 'About TRF',
 'About TRF',
 'About TRF',
 'About TRF',
 'About TRF',
 'About TRF',
 'About TRF',
 'About TRF',
 'About TRF',
 'About TRF',
 'About TRF',
 'About TRF',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'Goodbye_Thanks',
 'About',
 'About',
 'About',
 'About',
 'About',
 'About',
 'About',
 'About',
 'About',
 'Robocon',
 'Robocon',
 'Robocon',
 'Robocon',
 'Robocon',
 'Robocon',
 'Robocon',
 'Robocon',
 'Robocon',
 'Robocon',
 'Part of TRF ',
 'Part of TRF ',
 'Part of TRF ',
 'Part of TRF ',
 'Part of TRF 

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(training_labels)
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded2 = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded2)
print(onehot_encoded)

[[0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0.

In [ ]:
vocab_size = 1000
embedding_dim = 16
max_len = 20
oov_token = "<OOV>"
#OOV- Out of Vocab

tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_token)
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(training_sentences)
padded_sequences = pad_sequences(sequences, truncating='post', maxlen=max_len)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, onehot_encoded, test_size = 0.20, random_state = 0, stratify=onehot_encoded)

In [ ]:
print(X_test.shape,X_train.shape)

(16, 20) (62, 20)


In [ ]:
print(y_test.shape,y_train.shape)

(16, 6) (62, 6)


In [ ]:
model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length=max_len))
model.add(GlobalAveragePooling1D())
model.add(Dense(16, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(6, activation='softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 16)            16000     
                                                                 
 global_average_pooling1d (G  (None, 16)               0         
 lobalAveragePooling1D)                                          
                                                                 
 dense (Dense)               (None, 16)                272       
                                                                 
 dense_1 (Dense)             (None, 16)                272       
                                                                 
 dense_2 (Dense)             (None, 6)                 102       
                                                                 
Total params: 16,646
Trainable params: 16,646
Non-trainable params: 0
____________________________________________________

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()
epochs=500
history=model.fit(X_train, y_train, batch_size=32, epochs=epochs,validation_data=(X_test,y_test))

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 16)            16000     
                                                                 
 global_average_pooling1d (G  (None, 16)               0         
 lobalAveragePooling1D)                                          
                                                                 
 dense (Dense)               (None, 16)                272       
                                                                 
 dense_1 (Dense)             (None, 16)                272       
                                                                 
 dense_2 (Dense)             (None, 6)                 102       
                                                                 
Total params: 16,646
Trainable params: 16,646
Non-trainable params: 0
____________________________________________________